import { EventEmitter, ElementRef, OnInit, OnDestroy, OnChanges, SimpleChanges, AfterViewInit, NgZone, ChangeDetectorRef } from '@angular/core';
import { GoeyToastPhase, GoeyToastType, GoeyToastAction, GoeyToastClassNames, GoeyToastTimings } from './goey-toast.types';
import * as i0 from "@angular/core";
export declare class GoeyToastComponent implements OnInit, OnDestroy, AfterViewInit, OnChanges {
    private ngZone;
    private cdr;
    title: string;
    description?: string;
    type: GoeyToastType;
    phase: GoeyToastPhase;
    action?: GoeyToastAction;
    icon?: string;
    classNames?: GoeyToastClassNames;
    fillColor?: string;
    borderColor?: string;
    borderWidth?: number;
    timing?: GoeyToastTimings;
    duration?: number;
    spring: boolean;
    bounce: number;
    toastId?: string | number;
    position: string;
    showClose: boolean;
    dismissed: EventEmitter<void>;
    actionClicked: EventEmitter<void>;
    wrapperRef: ElementRef<HTMLDivElement>;
    pathRef: ElementRef<SVGPathElement>;
    headerRef: ElementRef<HTMLDivElement>;
    contentRef: ElementRef<HTMLDivElement>;
    showBody: boolean;
    actionSuccess: string | null;
    dismissing: boolean;
    hovered: boolean;
    currentPath: string;
    svgWidth: number;
    svgHeight: number;
    private morphCtrl;
    private pillResizeCtrl;
    private blobSquishCtrl;
    private shakeCtrl;
    private morphT;
    private aDims;
    private dimsRef;
    private expandedDimsRef;
    private collapsingRef;
    private preDismissRef;
    private collapseEndTime;
    private lastSquishTime;
    private mountSquished;
    private prevShowBody;
    private prevPhase;
    private dismissTimer;
    private remainingTime;
    private timerStart;
    private startX;
    private dragOffset;
    private isDragging;
    private onMouseMoveBound;
    private onMouseUpBound;
    private resizeObserver?;
    private destroyed;
    get isRight(): boolean;
    get isCenter(): boolean;
    get effectiveTitle(): string;
    get effectivePhase(): GoeyToastPhase;
    get effectiveDescription(): string | undefined;
    get effectiveAction(): GoeyToastAction | undefined;
    get isExpanded(): boolean;
    get effectiveFillColor(): string;
    get effectiveBorderColor(): string;
    get effectiveBorderWidth(): number;
    get titleColorClass(): string;
    get actionColorClass(): string;
    constructor(ngZone: NgZone, cdr: ChangeDetectorRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    onMouseEnter(): void;
    onMouseLeave(): void;
    onActionClick(): void;
    onTouchStart(e: TouchEvent): void;
    onTouchMove(e: TouchEvent): void;
    onTouchEnd(): void;
    onMouseDown(e: MouseEvent): void;
    private onMouseMove;
    private onMouseUp;
    private startDrag;
    private moveDrag;
    private endDrag;
    onCloseClick(e: Event): void;
    private measure;
    private flush;
    private startExpandMorph;
    private startCollapseMorph;
    private triggerLandingSquish;
    private triggerErrorShake;
    private startDismissTimer;
    private getFullDelay;
    static ɵfac: i0.ɵɵFactoryDeclaration<GoeyToastComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<GoeyToastComponent, "goey-toast", never, { "title": { "alias": "title"; "required": false; }; "description": { "alias": "description"; "required": false; }; "type": { "alias": "type"; "required": false; }; "phase": { "alias": "phase"; "required": false; }; "action": { "alias": "action"; "required": false; }; "icon": { "alias": "icon"; "required": false; }; "classNames": { "alias": "classNames"; "required": false; }; "fillColor": { "alias": "fillColor"; "required": false; }; "borderColor": { "alias": "borderColor"; "required": false; }; "borderWidth": { "alias": "borderWidth"; "required": false; }; "timing": { "alias": "timing"; "required": false; }; "duration": { "alias": "duration"; "required": false; }; "spring": { "alias": "spring"; "required": false; }; "bounce": { "alias": "bounce"; "required": false; }; "toastId": { "alias": "toastId"; "required": false; }; "position": { "alias": "position"; "required": false; }; "showClose": { "alias": "showClose"; "required": false; }; }, { "dismissed": "dismissed"; "actionClicked": "actionClicked"; }, never, never, true, never>;
}
